### ISSUE TITLE
After installing the Tor browser via flatpak on Distro Deepin 20.6 it does not open

### ISSUE THREAD

**Issue by serial02** [flathub/com.github.micahflee.torbrowser-launcher#36] opened 2022-06-02 14:55 UTC
Hello everybody

 After installing Tor browser via flatpak on Distro Deepin 20.6 it does not open.
 After running tor via terminal through the flatpak command, the following error message appears.

 Follows log of the entire sequence from installation to opening the Tor application.

```
Deepin@Deepin-PC:~$ flatpak install flathub com.github.micahflee.torbrowser-launcher
Looking for matches…

com.github.micahflee.torbrowser-launcher permissions:
    ipc                    network        fallback-x11        pulseaudio
    wayland                x11            dri                 file access [1]
    dbus access [2]

    [1] xdg-config/kdeglobals:ro, xdg-download
    [2] com.canonical.AppMenu.Registrar, org.kde.kconfig.notify


        ID                                       Arch   Ramo   Remote  Baixar
 1. [✓] com.github.micahflee.torbrowser-launcher x86_64 stable flathub 8,7 MB / 8,7 MB

Installation complete.
Deepin@Deepin-PC:~$ flatpak run com.github.micahflee.torbrowser-launcher
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.3.5
https://github.com/micahflee/torbrowser-launcher
Creating GnuPG homedir /home/Deepin/.var/app/com.github.micahflee.torbrowser-launcher/data/torbrowser/gnupg_homedir
Downloading Tor Browser for the first time.
Downloading https://aus1.torproject.org/torbrowser/update_3/release/Linux_x86_64-gcc3/x/en-US
Latest version: 11.0.13
Downloading https://dist.torproject.org/torbrowser/11.0.13/tor-browser-linux64-11.0.13_pt-BR.tar.xz.asc
Downloading https://dist.torproject.org/torbrowser/11.0.13/tor-browser-linux64-11.0.13_pt-BR.tar.xz
Verifying Signature
Downloading latest Tor Browser signing key...
Key imported successfully
Extracting tor-browser-linux64-11.0.13_pt-BR.tar.xz
Running /home/Deepin/.var/app/com.github.micahflee.torbrowser-launcher/data/torbrowser/tbb/x86_64/tor-browser_pt-BR/start-tor-browser.desktop
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/torbrowser_launcher/launcher.py", line 442, in success
    self.run_task()
  File "/app/lib/python3.9/site-packages/torbrowser_launcher/launcher.py", line 301, in run_task
    self.run()
  File "/app/lib/python3.9/site-packages/torbrowser_launcher/launcher.py", line 488, in run
    subprocess.call(
  File "/usr/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] Arquivo ou diretório inexistente: '/home/Deepin/.var/app/com.github.micahflee.torbrowser-launcher/data/torbrowser/tbb/x86_64/tor-browser_pt-BR/start-tor-browser.desktop'
Deepin@Deepin-PC:~$ flatpak run com.github.micahflee.torbrowser-launcher
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.3.5
https://github.com/micahflee/torbrowser-launcher
Launching Tor Browser.
Running /home/Deepin/.var/app/com.github.micahflee.torbrowser-launcher/data/torbrowser/tbb/x86_64/tor-browser_pt-BR/start-tor-browser.desktop
Traceback (most recent call last):
  File "/app/bin/torbrowser-launcher", line 30, in <module>
    torbrowser_launcher.main()
  File "/app/lib/python3.9/site-packages/torbrowser_launcher/__init__.py", line 87, in main
    gui = Launcher(common, app, url_list)
  File "/app/lib/python3.9/site-packages/torbrowser_launcher/launcher.py", line 167, in __init__
    self.update()
  File "/app/lib/python3.9/site-packages/torbrowser_launcher/launcher.py", line 214, in update
    self.start(None)
  File "/app/lib/python3.9/site-packages/torbrowser_launcher/launcher.py", line 233, in start
    self.run_task()
  File "/app/lib/python3.9/site-packages/torbrowser_launcher/launcher.py", line 301, in run_task
    self.run()
  File "/app/lib/python3.9/site-packages/torbrowser_launcher/launcher.py", line 488, in run
    subprocess.call(
  File "/usr/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] Arquivo ou diretório inexistente: '/home/Deepin/.var/app/com.github.micahflee.torbrowser-launcher/data/torbrowser/tbb/x86_64/tor-browser_pt-BR/start-tor-browser.desktop'
Deepin@Deepin-PC:~$ /home/Deepin/.var/app/com.github.micahflee.torbrowser-launcher/data/torbrowser/tbb/x86_64/tor-browser_pt-BR/start-tor-browser.desktop
bash: /home/Deepin/.var/app/com.github.micahflee.torbrowser-launcher/data/torbrowser/tbb/x86_64/tor-browser_pt-BR/start-tor-browser.desktop: /usr/bin/env: interpretador incorreto: Arquivo ou diretório inexistente
Deepin@Deepin-PC:~$ tor-browser_pt-BR/start-tor-browser.desktop
bash: tor-browser_pt-BR/start-tor-browser.desktop: Arquivo ou diretório inexistente
Deepin@Deepin-PC:~$
```

**Comment by AsciiWolf** [comment] 2022-06-02 17:02
Thanks for your report. It looks like that there is something broken on your system. Try removing the `~/.var/app/com.github.micahflee.torbrowser-launcher` directory.

**Comment by serial02** [comment] 2022-06-02 17:47
> Thanks for your report. It looks like that there is something broken on your system. Try removing the `~/.var/app/com.github.micahflee.torbrowser-launcher` directory.

And how I do it?  Removing Tor flatpak installation?
 The official Flatpak pages only teach how to install and not remove.

**Comment by AsciiWolf** [comment] 2022-06-02 17:50
Just open the File Manager application, to the address bar (should be activated using CTRL + L) enter `~/.var/app/`, then select the `com.github.micahflee.torbrowser-launcher` directory and remove it. Then launch Tor Browser.

**Comment by serial02** [comment] 2022-06-02 18:10
> Just open the File Manager application, to the address bar (should be activated using CTRL + L) enter `~/.var/app/`, then select the `com.github.micahflee.torbrowser-launcher` directory and remove it. Then launch Tor Browser again.

Hello

 Negative!  I did what was requested, where it reinstalls Tor again by downloading new version and does not open either by clicking through the application or via terminal with run Flatpak


```
Deepin@Deepin-PC:~$ flatpak run com.github.micahflee.torbrowser-launcher
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.3.5
https://github.com/micahflee/torbrowser-launcher
Launching Tor Browser.
Running /home/Deepin/.var/app/com.github.micahflee.torbrowser-launcher/data/torbrowser/tbb/x86_64/tor-browser_pt-BR/start-tor-browser.desktop
Traceback (most recent call last):
  File "/app/bin/torbrowser-launcher", line 30, in <module>
    torbrowser_launcher.main()
  File "/app/lib/python3.9/site-packages/torbrowser_launcher/__init__.py", line 87, in main
    gui = Launcher(common, app, url_list)
  File "/app/lib/python3.9/site-packages/torbrowser_launcher/launcher.py", line 167, in __init__
    self.update()
  File "/app/lib/python3.9/site-packages/torbrowser_launcher/launcher.py", line 214, in update
    self.start(None)
  File "/app/lib/python3.9/site-packages/torbrowser_launcher/launcher.py", line 233, in start
    self.run_task()
  File "/app/lib/python3.9/site-packages/torbrowser_launcher/launcher.py", line 301, in run_task
    self.run()
  File "/app/lib/python3.9/site-packages/torbrowser_launcher/launcher.py", line 488, in run
    subprocess.call(
  File "/usr/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] Arquivo ou diretório inexistente: '/home/Deepin/.var/app/com.github.micahflee.torbrowser-launcher/data/torbrowser/tbb/x86_64/tor-browser_pt-BR/start-tor-browser.desktop'
```


![Capturar_dde-file-manager_20220602145709](https://user-images.githubusercontent.com/32621790/171697029-8ca5486f-76b9-4ada-ac31-82e00edb3240.png)


![Capturar_20220602145408](https://user-images.githubusercontent.com/32621790/171697032-6746f3ab-e9a8-4e8c-ba73-f464c75d7d54.png)

**Comment by AsciiWolf** [comment] 2022-06-02 21:22
Hmm. I am afraid I am not able to help you. :-/ This really seems to be related to your system. What Flatpak version (flatpak --version) do you have?

**Comment by serial02** [comment] 2022-06-03 15:10
> Hmm. I am afraid I am not able to help you. :-/ This really seems to be related to your system. What Flatpak version (`flatpak --version`) do you have?

Hi,

Apparently this flatpak version is out of date

Can you update it

Deepin@Deepin-PC:$ flatpak --version
Flatpak 1.2.5
Deepin@Deepin-PC:$

Apparently other flatpaks applications are having this same problem due to the lack of update of the Deepin Official Distro Base 20.6, as can be seen here: ( https://github.com/linuxdeepin/developer-center/issues/3211 )

I'm on another VM and I still don't know if this has been fixed or updated. Caso este seja o problema! In case this is the problem!

**Comment by AsciiWolf** [comment] 2022-06-03 17:18
> Apparently this flatpak version is out of date

I am afraid I am not able to update it - it is your system Flatpak version. :-) The issue you linked is a different problem, but is probably caused by the same thing - Flatpak in Deepin is too old. However there is nothing I can do about it and no workaround (other than updating Flatpak in Deepin) available. Sorry. I am closing this issue.

**Closed by AsciiWolf** 2022-06-03 17:18 UTC
